development:
  dialect: postgres
  database: history
  user: postgres
  password: enter
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:enter@127.0.0.1:5432/samplebuffalo_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/samplebuffalo_production?sslmode=disable"}}
